### ISSUE TITLE
Minor typo in "How to Create a Simple CRUD App with Rails and React" Tutorial

### ISSUE THREAD

**Issue by dcamposliz** [jameshibbard/blog#1]
Hey @jameshibbard, 

I am really enjoying your tutorial, thanks for posting it!

I found a small typo:

![screen shot 2019-02-14 at 3 17 07 pm](https://user-images.githubusercontent.com/3254723/52815052-a33f9d80-306b-11e9-9851-23eaa4de4b3e.png)

I think instead of `application.erb.html` you probably meant `application.html.erb`. Hope this helps!

Best,
David

**Comment by jameshibbard** [comment]
Oops. Good catch. I'll get that fixed. Thank you very much.
